export const steps = [
    {
        key: "base",
        title: "Persönliche Daten",
        fields: [
            "title",
            "firstName",
            "lastName",
            "birthDate",
            "street",
            "zip",
            "city",
            "email",
            "phonePrivate",
            "phoneWork",
            "profession",
            "employer",
            "insurance",
            "isFamilyMember",
            "relationshipToPrimaryInsured",
            "primaryInsuredFirstName",
            "primaryInsuredLastName",
            "hasSupplementaryInsurance",
            "supplementaryInsuranceName",
            "gpName",
            "gpPhone",
        ],
    },
    {
        key: "conditions",
        title: "Gesundheitliche Angaben",
        fields: [
            "highBloodPressure",
            "lowBloodPressure",
            "heartValveDefect",
            "heartValveReplacement",
            "pacemaker",
            "endocarditis",
            "heartSurgery",
            "severeNeutropenia",
            "coagulationDisorders",
            "organTransplant",
            "stemCellTransplant",
            "asthmaOrLungDisease",
            "diabetes",
            "thyroidDisease",
            "epilepsy",
            "nervousSystemDisease",
            "faintingSpells",
            "rheumaArthritis",
            "osteoporosis",
            "kidneyDisease",
            "cysticFibrosis",
            "drugDependency",
            "smoker",
            "otherDiseases",
            "otherDiseasesText",
        ],
    },
    {
        key: "infectionTherapy",
        title: "Infektionen & Therapien",
        fields: [
            "hivAids",
            "hepatitisLiverDisease",
            "tuberculosis",
            "otherInfectiousDisease",
            "otherInfectiousDiseaseText",
            "bisphosphonates",
            "chemoTherapy",
            "radiationTherapy",
            "highDoseSteroidsOrImmunosuppressants",
        ],
    },
    {
        key: "medsAllergies",
        title: "Medikamente & Allergien",
        fields: [
            "takesMedication",
            "medications",
            "allergyLocalAnesthesia",
            "allergyAntibiotics",
            "allergyPainkillers",
            "allergyMetals",
            "allergyNotes",
            "weightKg",
        ],
    },
    {
        key: "dental",
        title: "Zahnärztliche Anamnese",
        fields: [
            "headNeckInjuries",
            "headNeckSurgeries",
            "hadOrthodonticTreatment",
            "orthodonticTeethExtracted",
            "tmjComplaints",
            "cmd",
            "bleedingAfterDentalTreatment",
            "recentDentalXrays",
            "problemsAfterInjections",
            "teethLostByAccident",
            "jawInjuryOrFracture",
            "pregnant",
            "dentalNotes",
        ],
    },
    {
        key: "wishes",
        title: "Wünsche & Herkunft",
        fields: [
            "wantsConsultation",
            "consultationImplants",
            "consultationBleaching",
            "consultationCeramicGoldInlay",
            "consultationAmalgamReplacement",
            "consultationRootCanal",
            "consultationProstheticsCrownsBridges",
            "consultationOrthodontics",
            "sourceRecommendation",
            "sourceInternet",
            "sourcePhoneBook",
            "sourceOther",
            "sourceOtherText",
            "usedSearchTerms",
        ],
    },
    {
        key: "consent",
        title: "Einwilligungen",
        fields: [
            "consentSmsReminder",
            "consentRecallSystem",
            "confirmWillInformChanges",
            "consentAppointmentPolicy",
            "consentDataProcessing",
        ],
    },
    { key: "review", title: "Zusammenfassung", fields: [] },
    { key: "thankyou", title: "Abschluss", fields: [] },
];
